// ── Route Index — mounts all routers under /api/v1 ──
// DO NOT EDIT THIS FILE — shared across all developers

const router = require('express').Router();

router.use('/auth', require('./auth.routes'));
router.use('/vehicles', require('./vehicle.routes'));
router.use('/drivers', require('./driver.routes'));
router.use('/trips', require('./trip.routes'));
router.use('/maintenance', require('./maintenance.routes'));
router.use('/fuel-logs', require('./fuelLog.routes'));
router.use('/expenses', require('./expense.routes'));
router.use('/reports', require('./report.routes'));
router.use('/dashboard', require('./dashboard.routes'));
router.use('/notifications', require('./notification.routes'));
router.use('/', require('./user.routes')); // /users, /activity-logs, /settings

module.exports = router;
